---
title: "Analysis on Exercise Data"
author: "SNTag"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document:
    number_sections: true
    toc: true
    toc_depth: 3
    fig_caption: true
    fig_width: 7
    fig_height: 4.5
---

```{R self_running, eval=FALSE, include = FALSE}
knitr::purl("./prediction-assignment.Rmd")
source("./prediction-assignment.R")
```

```{R loading_data, echo = F, eval = T}
library(tidyverse)
library(magrittr)

df_train <- read_csv("./data/pml-training.csv")
df_test  <- read_csv("./data/pml-testing.csv")

df_train$classe <- df_train$classe %>% as.factor

set.seed("1701")
```

# Introduction

This project will attempt to identify exercise regimes followed from biological data. This will
give us a guide to what is necessary for proper development.

Goal: to identify the exercise regime identified in the classe variable.

# Exploratory data analysis

The training data for this project has `r dim(df_train)[1]` entries, belonging
to `r df_train$user_name %>% unique %>% length`. We are interested in using this data to predict
how `r dim(df_test)[1]` entries should look.

In a quick test to check distribution of NAs, 2/3rds of the columns are nearly entirely NA, with
only some data. None are entirely NAs though.

```{R checking_for_NAs, echo = F, eval = T}
missing_values <- df_train %>% summarize_all(funs(sum(is.na(.))/dim(df_train)[1]))

missing_values <- gather(missing_values, key="feature", value="missing_pct")
missing_values %>%
  ggplot(aes(x=reorder(feature,-missing_pct),y=missing_pct)) +
  geom_bar(stat="identity",fill="red")+
    coord_flip()+theme_bw()
```

Further examination of the data shows that the same rows have NAs.

<!-- ```{R identify_rows_with_na, echo = F, eval = T} -->
<!-- for (i in 1:dim(missing_values)[1]) { -->
<!--     if (missing_values[i,2] > 0) { -->
<!--         if (exists("tmpVal")) { -->
<!--             which(!is.na(df_train[,tmpVal])) == which(!is.na(df_train[,i])) %>% print() -->
<!--             tmpVal <- i -->
<!--         } else {tmpVal <- i} -->
<!--     } -->
<!-- } -->
<!-- ``` -->

When determining correlation, we want only the numerical values. We subset those columns before
generating the correlation.

```{R numeric_sorting, echo = F, eval = T}
df_train_logic <- sapply(df_train, is.numeric)
df_train_num  <- df_train[ ,df_train_logic]
```
```{R corr_analysis}
correlations <- cor(df_train_num, df_train$classe)
bestCorrelations <- subset(as.data.frame(as.table(correlations)), abs(Freq)>0.3)
bestCorrelations
```
